### ISSUE TITLE
OpenWRT

### ISSUE THREAD

**Issue by Pimmetje** [schollz/find#154]
Hi i was wondering without reading the docs in too much detail (i am sorry if i overlooked it). But could openwrt be used with find like raspberry pi? This would allow for a very broad range of possible wifi data gather points. What data is needed from the wifi devices?

**Comment by TheMegaTB** [comment]
The device basically needs to do a scan for other WiFi networks and send the resulting MAC -> RSSI values to a server. I'm not too familiar with OpenWRT but it should be possible to integrate it. I am not sure if that's what you are trying to achieve though since that would determine the location of the OpenWRT device, not of its clients.

**Comment by Pimmetje** [comment]
No i would like to have the location of the wifi clients surrounding a few openwrt boxes like with the Raspberry Pi's. But what data does find need? Only single strength and MAC from all wifi devices or something special?

**Comment by TheMegaTB** [comment]
Ah nvmd so you are referring to [this](https://github.com/schollz/find-lf) project instead. Afaik it is required to get the probe requests every WiFi devices sends out. Can't tell you any details though. You might want to have a look at the linked repo.

**Comment by Pimmetje** [comment]
I missed that thanks
